#!/usr/bin/env bash
# Extracts the enclave's MRENCLAVE from the signed binary's SIGSTRUCT
# and emits a C header the client pins against.
#
# Uses `sgx_sign dump` (reads the .signed.so file — no enclave runtime
# needed) so it works in both SIM and HW modes, and in HW even on
# machines that don't actually have SGX. The value matches what the
# enclave reports at runtime via sgx_create_report.
#
# Re-run after every enclave rebuild (Makefile already wires this).

set -euo pipefail

cd "$(dirname "$0")/.."

SGX_SDK="${SGX_SDK:-/opt/intel/sgxsdk}"
SGX_SIGN="$SGX_SDK/bin/x64/sgx_sign"

if [[ ! -x "$SGX_SIGN" ]]; then
    echo "extract_mrenclave: $SGX_SIGN not found — set SGX_SDK env var" >&2
    exit 1
fi
if [[ ! -f enclave.signed.so ]]; then
    echo "extract_mrenclave: enclave.signed.so missing — run 'make enclave' first" >&2
    exit 1
fi

DUMP=$(mktemp)
trap 'rm -f "$DUMP"' EXIT
"$SGX_SIGN" dump -enclave enclave.signed.so -dumpfile "$DUMP" >/dev/null

# enclave_hash.m is two lines of 16 "0xNN" tokens following the label.
HEX=$(grep -A 2 'enclave_hash.m:' "$DUMP" \
      | tail -n 2 \
      | tr -d ' \n' \
      | sed 's/0x//g')

if [[ ! "$HEX" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "extract_mrenclave: failed to parse MRENCLAVE from sgx_sign dump (got: $HEX)" >&2
    exit 1
fi

OUT=Include/expected_mrenclave.h
{
    echo "/* AUTO-GENERATED by scripts/extract_mrenclave.sh — do not edit. */"
    echo "/* Regenerate after every enclave rebuild. */"
    echo "#ifndef _SAHC_EXPECTED_MRENCLAVE_H_"
    echo "#define _SAHC_EXPECTED_MRENCLAVE_H_"
    echo
    echo "#include <stdint.h>"
    echo
    echo "static const uint8_t EXPECTED_MRENCLAVE[32] = {"
    printf "    "
    for (( i=0; i<32; i++ )); do
        BYTE="0x${HEX:$((i*2)):2}"
        printf "%s," "$BYTE"
        if (( (i+1) % 8 == 0 && i != 31 )); then printf "\n    "; fi
    done
    printf "\n};\n\n"
    echo "#endif"
} > "$OUT"

echo "extract_mrenclave: wrote $OUT (mrenclave=$HEX)"
