#!/usr/bin/env bash
# Extracts the enclave's MRENCLAVE and emits a C header the client
# pins against. Runs `./sgx_server --print-mrenclave` (which loads
# the signed enclave and reads sgx_create_report) and writes the
# hex bytes into Include/expected_mrenclave.h.
#
# Re-run after every enclave rebuild (Makefile already wires this).

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -x ./sgx_server ]]; then
    echo "extract_mrenclave: sgx_server binary missing — run 'make sgx_server' first" >&2
    exit 1
fi
if [[ ! -f enclave.signed.so ]]; then
    echo "extract_mrenclave: enclave.signed.so missing — run 'make enclave' first" >&2
    exit 1
fi

HEX=$(./sgx_server --print-mrenclave 2>/dev/null | tail -n1)
if [[ ! "$HEX" =~ ^[0-9a-f]{64}$ ]]; then
    echo "extract_mrenclave: unexpected output from sgx_server (got: $HEX)" >&2
    exit 1
fi

OUT=Include/expected_mrenclave.h
{
    echo "/* AUTO-GENERATED by scripts/extract_mrenclave.sh — do not edit.  */"
    echo "/* Regenerate after every enclave rebuild. */"
    echo "#ifndef _SAHC_EXPECTED_MRENCLAVE_H_"
    echo "#define _SAHC_EXPECTED_MRENCLAVE_H_"
    echo
    echo "#include <stdint.h>"
    echo
    echo "static const uint8_t EXPECTED_MRENCLAVE[32] = {"
    printf "    "
    for (( i=0; i<32; i++ )); do
        BYTE="0x${HEX:$((i*2)):2}"
        printf "%s," "$BYTE"
        if (( (i+1) % 8 == 0 && i != 31 )); then printf "\n    "; fi
    done
    printf "\n};\n\n"
    echo "#endif"
} > "$OUT"

echo "extract_mrenclave: wrote $OUT (mrenclave=$HEX)"
