#!/usr/bin/env bash
# Extracts MRENCLAVE from gramine_server.sig and emits Include/expected_mrenclave.h.
# Used when SAHC_HW=1 (DCAP path) — the client pin must match the Gramine
# enclave actually running, not the SDK enclave.signed.so.

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -f gramine_server.sig ]]; then
    echo "extract_gramine_mrenclave: gramine_server.sig missing — run 'make gramine_manifest_hw' first" >&2
    exit 1
fi

HEX=$(gramine-sgx-sigstruct-view --output-format json gramine_server.sig \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["mr_enclave"])')

if [[ ! "$HEX" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "extract_gramine_mrenclave: failed to parse mr_enclave (got: $HEX)" >&2
    exit 1
fi

OUT=Include/expected_mrenclave_gramine.h
{
    echo "/* AUTO-GENERATED by scripts/extract_gramine_mrenclave.sh — do not edit. */"
    echo "/* Source: gramine_server.sig — used by client when SAHC_HW=1. */"
    echo "#ifndef _SAHC_EXPECTED_MRENCLAVE_H_"
    echo "#define _SAHC_EXPECTED_MRENCLAVE_H_"
    echo
    echo "#include <stdint.h>"
    echo
    echo "static const uint8_t EXPECTED_MRENCLAVE[32] = {"
    printf "    "
    for (( i=0; i<32; i++ )); do
        BYTE="0x${HEX:$((i*2)):2}"
        printf "%s," "$BYTE"
        if (( (i+1) % 8 == 0 && i != 31 )); then printf "\n    "; fi
    done
    printf "\n};\n\n"
    echo "#endif"
} > "$OUT"

echo "extract_gramine_mrenclave: wrote $OUT (mrenclave=$HEX)"
